#!/usr/bin/env python3

# Copyright 2017 CodiLime
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
from pprint import pprint

from veles.data.bindata import BinData
from veles.dis.isa.falcon import FalconIsa
from veles.dis.sema import SemaVar

data = []
for x in sys.argv[1:]:
    data.append(int(x, 16))

pos = 0
while pos < len(data):
    base = SemaVar(32, 'aaa')
    res = FalconIsa().parse(BinData(8, data), 0, base, pos)
    # pprint(res.__dict__)
    print('{:08x} {:18} {}'.format(pos, ' '.join(format(x, '02x') for x in data[pos:pos+res.len]), (' '*28 + '\n').join(str(x) for x in res.insns)))
    pos += res.len
    print(res.sema.str(0))
